# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a01f4dfc3562ba924ddcd0c95722a6ccb762e199a87339ec84625d06327d85307e1ebe3db6dd3c435e26c23a109b6bd499f3cc91172721108664edb717a3e08

test:
  secret_key_base: 37727c616623609ca604f693539ddae2b91525a87cc34880c54b331b703af344f52cc05e49a4599c1b4a4730790412a0efa5d89f3ee249aeb35cc5b9374b62c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
